# SPDX-FileCopyrightText: 2026 Avish Jha <avish.j@pm.me>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

sonar.projectKey=avishj_optifli
sonar.organization=avishj
sonar.projectName=optifli

sonar.python.version=3.13, 3.14

sonar.sources=src/
sonar.tests=tests/

sonar.python.coverage.reportPaths=\
    coverage-*-unit.xml,\
    coverage-*-integration.xml,\
    coverage-*-e2e.xml

sonar.python.xunit.reportPath=results-*-*.xml

sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300

sonar.sourceEncoding=UTF-8
